"""add permissions and product_code

Revision ID: 2201d6227d4c
Revises: 54a3c2df4a54
Create Date: 2026-05-20 10:34:14.297302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2201d6227d4c'
down_revision = '54a3c2df4a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_code', sa.String(length=100), nullable=True))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.Text(), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sell_price', sa.Float(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('classic_customer',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('classic_customer',
               existing_type=sa.String(length=20),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('sell_price')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.drop_column('product_code')

    # ### end Alembic commands ###
