"""add basic_salary column

Revision ID: 54a3c2df4a54
Revises: 
Create Date: 2026-05-06 10:44:01.052778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a3c2df4a54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_salary', sa.Float(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classic_customer', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('classic_customer')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('basic_salary')

    # ### end Alembic commands ###
